### ISSUE TITLE
Not working in Linux Mint 17.3

### ISSUE THREAD

**Issue by pebmp17** [michaldaniel/Ebook-Viewer#14]
Hi, I have all the 3 dependencies and used the `sudo make install` but I couldn't get it to run. Opening as a default app in a epub file doesn't even show the program window and using it in terminal gave me this error below. Any known issues with Linux Mint or Ubuntu 14.04?

`Traceback (most recent call last):
  File "/usr/share/easy-ebook-viewer/main.py", line 28, in <module>
    win = MainWindow()
  File "/usr/share/easy-ebook-viewer/main_window.py", line 59, in __init__
    self.header_bar_component = header_bar.HeaderBarComponent(self)
  File "/usr/share/easy-ebook-viewer/components/header_bar.py", line 38, in __init__
    self.__populate_headerbar()
  File "/usr/share/easy-ebook-viewer/components/header_bar.py", line 61, in __populate_headerbar
    self.current_page_entry.set_max_width_chars(3)
AttributeError: 'Entry' object has no attribute 'set_max_width_chars'
`

**Comment by michaldaniel** [comment]
set_max_width_chars was added with GTK+ 3.12

What is the output of `dpkg -s libgtk-3-0|grep '^Version'` for you?

**Comment by pebmp17** [comment]
That was quick,
The output is: `Version: 3.10.8~8+qiana` 
Which seems like I'm not going to be able to use it for some time, right? =\

**Comment by michaldaniel** [comment]
No, I'm going to push update in few minutes. I'll catch this error and you will enjoy it with hideous oversized entry elements in the header in the worst case scenario. In the best one I'll soon figure out how to pack those elements so it will sill display correctly. Stay tuned.

**Comment by pebmp17** [comment]
lol, hope so! I will wait, hope everything goes well on your side.

**Comment by michaldaniel** [comment]
No matter what I do Gtk.HeaderBar doesn't let me pack things with control over their expand and fill like any other container does. This is why I used that property the first time to limit their size.
Setting hexpand and haling doesn't do anything either.
```
self.current_page_entry.set_hexpand(False)
self.current_page_entry.set_halign(Gtk.Align.START) 
```

I'm going to leave it tagged as help wanted for some time, if no one picks it up I'll have to close this on release.

**Comment by pebmp17** [comment]
Nope, It doesn't. Same thing, just a different error

`Traceback (most recent call last):
  File "/usr/share/easy-ebook-viewer/main.py", line 28, in <module>
    win = MainWindow()
  File "/usr/share/easy-ebook-viewer/main_window.py", line 116, in __init__
    self.load_book_data(sys.argv[1])
  File "/usr/share/easy-ebook-viewer/main_window.py", line 332, in load_book_data
    self.__continiue_book_loading(filename)
  File "/usr/share/easy-ebook-viewer/main_window.py", line 284, in __continiue_book_loading
    self.chapters_list_component.reload_listbox()
  File "/usr/share/easy-ebook-viewer/components/chapters_list.py", line 85, in reload_listbox
    self.__populate_listbox()
  File "/usr/share/easy-ebook-viewer/components/chapters_list.py", line 67, in __populate_listbox
    self.__window.content_provider.titles[i][1]))
  File "/usr/share/easy-ebook-viewer/components/chapters_list.py", line 40, in __init__
    label.set_margin_start(10)
AttributeError: 'Label' object has no attribute 'set_margin_start'
`

**Comment by michaldaniel** [comment]
Oh boy, this is another thing I think was added recently. This is getting a bit ridiculous, I'll look into this tomorrow. The only solution can be to use CSS for margin styling those labels witch I really wanted to avoid.

**Comment by pebmp17** [comment]
Wait a sec, I tried a different book and it sorta worked now. No text appears through, is this a good sign?

**Comment by michaldaniel** [comment]
@pebmp17 No, preferences will currently crash for you and chapters index and book loading spinner. They all use GTK+ 3.14 set_margin alternative to xpad property. It hard to tell right now what the code does since the exception is being thrown there for sure during book loading.

**Comment by pebmp17** [comment]
Ok then. Sure, take a rest, no need to hurry. You already tried to fix anyway. Also, you asked how old the mint is, did you mean the release date? I think it's from almost the end of 2015. The computer it's more than 10 years old btw.

**Comment by michaldaniel** [comment]
@pebmp17 I wouldn't be able to sleep anyway. It's good for testing now.

**Comment by pebmp17** [comment]
Well, it did work for a while after commit e9526bc, but after I updated again doesn't anymore

`Traceback (most recent call last):
  File "/usr/share/easy-ebook-viewer/main.py", line 28, in <module>
    win = MainWindow()
  File "/usr/share/easy-ebook-viewer/main_window.py", line 59, in __init__
    self.header_bar_component = header_bar.HeaderBarComponent(self)
  File "/usr/share/easy-ebook-viewer/components/header_bar.py", line 38, in __init__
    self.__populate_headerbar()
  File "/usr/share/easy-ebook-viewer/components/header_bar.py", line 76, in __populate_headerbar
    self.set_max_length(len(_("of 0"))+2)
AttributeError: 'HeaderBarComponent' object has no attribute 'set_max_length'
`

**Comment by michaldaniel** [comment]
@pebmp17 Sorry for using you as a build machine, I should have been more professional and set-up proper testing environment for this. Anyway, seems like we are really close, can you test preferences and see what is up?

**Comment by pebmp17** [comment]
No problem, I here to do wherever I can to help you solve this. So, seems you are right and everything is working again, but when I press the preferences button this appears in the terminal:

`Traceback (most recent call last):
  File "/usr/share/easy-ebook-viewer/components/header_bar.py", line 158, in __on_preferences_menu_item_clicked
    dialog.show_dialog(self.__window)
  File "/usr/share/easy-ebook-viewer/components/preferences_dialog.py", line 33, in show_dialog
    self.header_bar_component = HeaderBarComponent(self)
  File "/usr/share/easy-ebook-viewer/components/preferences_dialog.py", line 79, in __init__
    self.set_has_subtitle(True)
AttributeError: 'HeaderBarComponent' object has no attribute 'set_has_subtitle'`

**Comment by michaldaniel** [comment]
I had to take really longer break but it's all good now I think.

**Comment by pebmp17** [comment]
Well, I moved to Windows now, so no big deal.Thanks for fixing that anyway. Btw, I did had updated gtk for a couple weeks and with it your program ran perfectly, nice work.

**Comment by michaldaniel** [comment]
@pebmp17 Shame to see you go. Come back to Linux family one day.

**Comment by pebmp17** [comment]
Hahaha, I will come back for sure, but for now I sorta need to use Windows. Hope that Linux programs evolve a lot in this meantime.
